### PR TITLE
Change formal "Neutron Network Node" to "Gateway Node"

### PR DESCRIPTION
**Pull request by timfallmk**
Note: this only changes the human visible titles, not the filenames or
references. I didn’t want to break anything.

@yantarou Here's your PR for review.

### CODE REVIEW

**Comment by midosaba** [comment]
Thank you for contributing to MidoNet! MidoNet uses Gerrithub for code review. Please visit http://wiki.midonet.org/How%20to%20contribute and follow the instructions there to upload your change to Gerrithub.

**Comment by timfallmk** [comment]
Fuck you @midosaba

**Comment by timfallmk** [comment]
@midonet/owners Please reopen this PR. Who is responsible for @midosaba ?

**Comment by midosaba** [comment]
Thank you for contributing to MidoNet! MidoNet uses Gerrithub for code review. Please visit http://wiki.midonet.org/How%20to%20contribute and follow the instructions there to upload your change to Gerrithub.

**Pull request closed without merging**
